[mirrors]
# Conda mirrors
"https://repo.anaconda.com/pkgs/main" = ["https://mirrors.zju.edu.cn/anaconda/pkgs/main"]
"https://repo.anaconda.com/pkgs/free" = ["https://mirrors.zju.edu.cn/anaconda/pkgs/free"]
"https://conda.anaconda.org/conda-forge" = ["https://mirrors.zju.edu.cn/anaconda/cloud/conda-forge"]
"https://conda.anaconda.org/bioconda" = ["https://mirrors.zju.edu.cn/anaconda/cloud/bioconda"]

# PyPI mirrors
"https://pypi.org/simple" = ["https://mirrors.aliyun.com/pypi/simple"]

